<b>예제 2-22</b> numpy.ndarray에서 행과 열을 이용한 기본 연산

In [1]:
import numpy

a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
type(a)

numpy.ndarray

In [3]:
a.shape

(12,)

In [4]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
a[2]

array([ 8,  9, 10, 11])

In [6]:
a[2, 1]

9

In [7]:
a[:, 1]

array([1, 5, 9])

In [8]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

----
NumPy는 numpy.ndarray의 모든 요소를 저장, 로딩, 처리하는 고급 연산도 지원한다.

In [ ]:
import numpy

floats = numpy.loadtxt('floats-10M-lines.txt')
floats[-3:]
# array([ 3016362.69195522, 535281.10514262, 4566560.44373946 ])

floats *= .5
floats[-3:]
# array([ 1508181.34597761, 267640.55257131, 2283280.22186973 ])

from time import perf_counter as pc
t0 = pc(); floats /= 3; pc() - t0
# 0.03690556302899495

numpy.save('floats-10M', floats)
floats2 = numpy.load('floats-10M.npy', 'r+')
floats2 *= 6
floats2[-3:]
# array([ 3016362.69195522, 535281.10514262, 4566560.44373946 ])